# Generated by Django 3.0.8 on 2020-07-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xplore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xplore',
            name='loc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='xplore',
            name='mail',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='xplore',
            name='user',
            field=models.CharField(default='', max_length=255),
        ),
    ]
